### ISSUE TITLE
api/board 관련 수정 요청 드립니다

### ISSUE THREAD

**Issue by DoHi0512** [SooDongTae/tool_server#97]
### 🐞 Describe

api/board 의 post 요청시 response로 작성된 글의 id 넘겨주세요

api/board/list get요청시 boardResponseList에 글 id 넣어주세요

### 📄 Logs

```shell
X
```

### 🌏 Environment

X

### 🙋🏻 More

X

**Comment by soohyang136** [comment]
수정하였습니다.
